CLEAR SELECTION;
SET $usds = us_node_id + ds_node_id;
LIST $list;
SELECT DISTINCT $usds INTO $list;
LET $index=1;
WHILE $index <= LEN($list);
    SELECT count($usds=AREF($index,$list)) INTO $count;
    IIF($count>1,$usds=AREF($index,$list),'');
    LET $index=$index+1;
WEND;