LIST $oids STRING;
SELECT DISTINCT oid into $oids;
LET $i = 1;
LET $width = 0;
WHILE $i<=len($oids);
  DESELECT ALL;
  SELECT conduit_width into $width where oid=AREF($i,$oids);
  IF $width = 600;
    set conduit_width = 500 where oid=AREF($i,$oids);
  ELSEIF $width = 500;
    set conduit_width = 400 where oid=AREF($i,$oids);
  ELSE;
    set conduit_width = 100 where oid=AREF($i,$oids);
  ENDIF;
  LET $i = $i+1;
WEND; 