# hw_flow_survey_import_exchange.rb — Exchange-mode script
# Reads manifest.csv + CSV files generated by the UI script, then imports
# them into the ICM database as Flow Survey objects with child observed events.
#
# Usage: ICMExchange.exe hw_flow_survey_import_exchange.rb
#
# BEFORE RUNNING:
#   Set DB_PATH below, OR let the UI script write exchange_config.txt.
#   Set CSV_FOLDER to the csv_output folder if not using exchange_config.txt.

# ─── CONFIGURATION ───────────────────────────────────────────────────────────

DB_PATH    = 'D:\TEMP\Flow_Survey_Data\Standalone.icmm'   # ← e.g. 'C:/Projects/my_model.icmm'
CSV_FOLDER = ''         # ← leave blank to auto-detect from exchange_config.txt
ROOT_GROUP_NAME = 'Flow Survey Data'

# ─── HELPERS ─────────────────────────────────────────────────────────────────

def safe_puts(text)
  begin
    puts text.to_s.encode('CP850', :invalid => :replace, :undef => :replace, :replace => '?')
  rescue
    puts text.to_s.encode('ASCII', :invalid => :replace, :undef => :replace, :replace => '?')
  end
end

def banner(text)
  puts "\n#{'=' * 60}"
  puts "  #{text}"
  puts '=' * 60
end

# ─── LOCAL NAME REGISTRY ────────────────────────────────────────────────────
# .children doesn't refresh after import_new_model_object, so we track names
# locally to avoid collisions.

$name_registry = {}

def register_name(gkey, name)
  $name_registry[gkey] ||= {}
  $name_registry[gkey][name.downcase] = true
end

def name_taken?(gkey, name)
  return false unless $name_registry.key?(gkey)
  $name_registry[gkey].key?(name.downcase)
end

def load_existing_names(parent, gkey)
  return if $name_registry.key?(gkey)
  names = {}
  begin
    parent.children.each do |child|
      names[child.name.downcase] = true
    end
  rescue
  end
  $name_registry[gkey] = names
end

def unique_name(gkey, base_name)
  return base_name unless name_taken?(gkey, base_name)
  n = 2
  loop do
    candidate = "#{base_name} (#{n})"
    return candidate unless name_taken?(gkey, candidate)
    n += 1
  end
end

# ─── RESOLVE CONFIGURATION ──────────────────────────────────────────────────

banner('CONFIGURATION')

script_dir = File.dirname(File.expand_path(__FILE__))

# Try to find csv_output folder
csv_folder = CSV_FOLDER

if csv_folder.nil? || csv_folder.empty?
  # Check for exchange_config.txt in any csv_output subfolder
  config_candidates = Dir.glob("#{script_dir}/**/exchange_config.txt")
  if config_candidates.length > 0
    csv_folder = File.read(config_candidates[0]).strip
    puts "  Auto-detected CSV folder from config: #{csv_folder}"
  end
end

if csv_folder.nil? || csv_folder.empty?
  # Fallback: look for csv_output next to script
  candidate = File.join(script_dir, 'csv_output')
  if File.directory?(candidate)
    csv_folder = candidate
    puts "  Using csv_output folder next to script: #{csv_folder}"
  end
end

if csv_folder.nil? || csv_folder.empty? || !File.directory?(csv_folder)
  puts "FATAL: Cannot find CSV output folder."
  puts "  Set CSV_FOLDER at top of script, or ensure csv_output/ exists."
  exit
end

manifest_path = File.join(csv_folder, 'manifest.csv')
unless File.exist?(manifest_path)
  puts "FATAL: manifest.csv not found in #{csv_folder}"
  exit
end

db_path = DB_PATH
if db_path == 'SET_ME'
  puts "FATAL: Set DB_PATH at the top of this script."
  exit
end

puts "  DB_PATH    : #{db_path}"
puts "  CSV_FOLDER : #{csv_folder}"
puts "  MANIFEST   : #{manifest_path}"

# ─── READ MANIFEST ──────────────────────────────────────────────────────────

banner('READING MANIFEST')

events = []
header = nil

File.readlines(manifest_path).each do |line|
  line = line.strip
  next if line.empty?
  if header.nil?
    header = line.split(',')
    next
  end
  parts = line.split(',', -1)
  ev = {}
  header.each_with_index do |col, i|
    ev[col.strip] = (parts[i] || '').strip
  end
  events << ev
end

puts "  Events to import: #{events.length}"
events.each do |ev|
  puts "    - #{ev['event_name']}"
end

# ─── OPEN DATABASE ──────────────────────────────────────────────────────────

banner('OPENING DATABASE')

db = nil
begin
  db = WSApplication.open(db_path)
  if db
    puts "  Database opened successfully."
  else
    puts "FATAL: WSApplication.open returned nil."
    exit
  end
rescue => e
  puts "FATAL: #{e.class}: #{e.message}"
  exit
end

# ─── FIND OR CREATE ROOT MODEL GROUP ────────────────────────────────────────

banner('ROOT MODEL GROUP')

root_group = nil
db.root_model_objects.each do |obj|
  if obj.type == 'Model Group' && obj.name == ROOT_GROUP_NAME
    root_group = obj
    break
  end
end

if root_group
  puts "  Found existing: '#{root_group.name}'"
else
  puts "  Creating '#{ROOT_GROUP_NAME}'..."
  begin
    root_group = db.new_model_object('Model Group', ROOT_GROUP_NAME)
    if root_group
      puts "  Created successfully."
    else
      puts "FATAL: Could not create root Model Group."
      exit
    end
  rescue => e
    puts "FATAL: #{e.class}: #{e.message}"
    exit
  end
end

# ─── CREATE SUB-GROUPS ───────────────────────────────────────────────────────

banner('SUB-GROUPS')

# Flow Monitors and Depth Monitors sit under the root group
flow_mon_group = nil
depth_mon_group = nil

# Check for existing sub-groups
load_existing_names(root_group, 'root')

begin
  if name_taken?('root', 'Flow Monitors')
    root_group.children.each do |child|
      if child.type == 'Model Group' && child.name == 'Flow Monitors'
        flow_mon_group = child
        break
      end
    end
  end
  unless flow_mon_group
    flow_mon_group = root_group.new_model_object('Model Group', 'Flow Monitors')
    register_name('root', 'Flow Monitors')
  end
  puts "  Flow Monitors group: OK"
rescue => e
  puts "FATAL: Could not create Flow Monitors group: #{e.class}: #{e.message}"
  exit
end

begin
  if name_taken?('root', 'Depth Monitors')
    root_group.children.each do |child|
      if child.type == 'Model Group' && child.name == 'Depth Monitors'
        depth_mon_group = child
        break
      end
    end
  end
  unless depth_mon_group
    depth_mon_group = root_group.new_model_object('Model Group', 'Depth Monitors')
    register_name('root', 'Depth Monitors')
  end
  puts "  Depth Monitors group: OK"
rescue => e
  puts "FATAL: Could not create Depth Monitors group: #{e.class}: #{e.message}"
  exit
end

# Load existing children for name collision detection
load_existing_names(flow_mon_group, 'flow_mon')
load_existing_names(depth_mon_group, 'depth_mon')

# ─── IMPORT EVENTS ──────────────────────────────────────────────────────────

banner('IMPORTING EVENTS')

# Flow Monitor FS gets: Depth (F-monitors), Flow, Velocity, Rain
flow_mon_imports = [
  ['flow_csv',     'Observed Flow Event',     'Flow'],
  ['depth_csv',    'Observed Depth Event',    'Depth'],
  ['velocity_csv', 'Observed Velocity Event', 'Velocity'],
  ['rain_csv',     'Rainfall Event',          'Rain']
]

# Depth Monitor FS gets: Depth Only (D-monitors), Rain
depth_mon_imports = [
  ['depth_only_csv', 'Observed Depth Event', 'Depth Only'],
  ['rain_csv',       'Rainfall Event',       'Rain']
]

def create_fs_and_import(parent, parent_key, event_name, csv_folder, ev, import_list, counters)
  fs_name = unique_name(parent_key, event_name)
  register_name(parent_key, fs_name)

  fs = nil
  begin
    fs = parent.new_model_object('Flow Survey', fs_name)
    if fs
      puts "  Created Flow Survey: '#{fs_name}' in #{parent.name}"
    else
      puts "  ERROR: new_model_object returned nil for '#{fs_name}'"
      counters[:errors] += 1
      return
    end
  rescue => e
    puts "  ERROR creating Flow Survey: #{e.class}: #{e.message}"
    counters[:errors] += 1
    return
  end

  fs_key = "fs_#{parent.name}_#{fs_name}"
  $name_registry[fs_key] = {}

  import_list.each do |col, type_str, child_base|
    csv_name = ev[col]
    next if csv_name.nil? || csv_name.empty?

    csv_path = File.join(csv_folder, csv_name)
    unless File.exist?(csv_path)
      puts "  WARN: File not found — #{csv_path}"
      counters[:errors] += 1
      next
    end

    child_name = unique_name(fs_key, child_base)
    register_name(fs_key, child_name)

    begin
      obj = fs.import_new_model_object(type_str, child_name, 'CSV', csv_path)
      if obj
        puts "  + [#{type_str}] '#{child_name}' <- #{csv_name}"
        counters[:created] += 1
      else
        puts "  ERROR: import returned nil for '#{child_name}' (#{type_str})"
        counters[:errors] += 1
      end
    rescue => e
      puts "  ERROR importing '#{child_name}': #{e.class}: #{e.message}"
      counters[:errors] += 1
    end
  end
end

counters = { :created => 0, :errors => 0 }

events.each do |ev|
  event_name = ev['event_name']
  puts "\n--- Event: #{event_name} ---"

  # Flow Monitor FS (under Flow Monitors group)
  has_flow_data = ['flow_csv', 'depth_csv', 'velocity_csv'].any? { |c| ev[c] && !ev[c].empty? }
  if has_flow_data
    create_fs_and_import(flow_mon_group, 'flow_mon', event_name, csv_folder, ev, flow_mon_imports, counters)
  end

  # Depth Monitor FS (under Depth Monitors group)
  has_depth_only = ev['depth_only_csv'] && !ev['depth_only_csv'].empty?
  if has_depth_only
    create_fs_and_import(depth_mon_group, 'depth_mon', event_name, csv_folder, ev, depth_mon_imports, counters)
  end
end

# ─── SUMMARY ─────────────────────────────────────────────────────────────────

banner('IMPORT COMPLETE')
puts "  Events processed : #{events.length}"
puts "  Objects created  : #{counters[:created]}"
puts "  Errors           : #{counters[:errors]}"
puts '=' * 60
