#InfoWorks ICM Technical Information Hub

puts "1/ InfoWorks ICM Technical Information Hub for InfoWorks and SWMM Networks"
puts "https://boards.autodesk.com/4bf242?token=a671af9e76"
puts "Category                 ".ljust(30) + "Details"
puts "Support               ".ljust(30) + "Innovyze Support"
puts "                         ".ljust(30) + "Autodesk Support"
puts "Downloads             ".ljust(30) + "Innovyze Downloads Portal"
puts "                         ".ljust(30) + "Autodesk Downloads Portal"
puts "Versioning            ".ljust(30) + "Policy on Versioning"
puts "Release Info          ".ljust(30) + "What's New"
puts "                         ".ljust(30) + "Release Notes Post v2024.0"
puts "                         ".ljust(30) + "Known Issues"
puts "                         ".ljust(30) + "Release Notes Pre v2024.0"
puts "Roadmap               ".ljust(30) + "InfoWorks ICM Roadmap"
puts "                         ".ljust(30) + "Autodesk Water Solutions Roadmap"
puts "Licensing             ".ljust(30) + "Thales Licensing for InfoWorks ICM"
puts "                         ".ljust(30) + "Fixed Thales Licensing"
puts "                         ".ljust(30) + "Floating Thales Licensing"
puts "                         ".ljust(30) + "Autodesk Licensing"
puts "Technical Resources   ".ljust(30) + "Help Documentation"
puts "                         ".ljust(30) + "Knowledge Centered Services"
puts "                         ".ljust(30) + "System Requirements"
puts "                         ".ljust(30) + "Security Advisories"
puts "                         ".ljust(30) + "ICM Ideas Portal"
puts "2/ InfoWorks ICM Technical Information Hub for InfoWorks and SWMM Networks"
puts "https://boards.autodesk.com/4bf242?token=a671af9e76"
puts "Configuration          ".ljust(30) + "Innovyze Workgroup Products IT Architecture"
puts "                         ".ljust(30) + "Workgroup Data Server Administration"
puts "                         ".ljust(30) + "InfoWorks ICM Workgroup Best Practices"
puts "                         ".ljust(30) + "Configuration of Simulation Agents for InfoWorks"
puts "Learning               ".ljust(30) + "InfoWorks ICM On demand Training Course"
puts "                         ".ljust(30) + "InfoWorks ICM On demand Learning Units"
puts "                         ".ljust(30) + "InfoWorks ICM Basics tutorial series"
puts "                         ".ljust(30) + "One Water Blog"
puts "Scripting              ".ljust(30) + "Automation Scripts (GitHub)"
puts "                         ".ljust(30) + "InfoWorks ICM Exchange API"
puts "The Cloud              ".ljust(30) + "Ready to get started with our cloud capabilities?"
puts "                         ".ljust(30) + "Creating a Hub"
puts "                         ".ljust(30) + "Cloud vs On premise Database"
puts "                         ".ljust(30) + "Cloud Connection Requirements"
puts "                         ".ljust(30) + "Cloud Simulation Usage"                  
