################################################################################
# zone_schematic_html.rb
# Generates the interactive vis-network HTML page for the area schematic.
# Loaded via require_relative from zone_schematic.rb
# Depends on: zone_schematic_helpers.rb (must be loaded first)
################################################################################

# Generate the complete HTML string for the area schematic.
# Params:
#   html_payload  - Hash with :nodes and :edges arrays
#   network_name  - display name of the network
#   safe_name     - sanitized filename stem (used for HTML filename and storage key)
#   layout_preloaded - true if positions were loaded from a previous HTML
#   nodes_payload - the nodes array (needed to embed layout positions)
def generate_zone_html(html_payload, network_name, safe_name, layout_preloaded, nodes_payload)
  html_filename = "#{safe_name}.html"
  esc_name = network_name.gsub('"', '&quot;').gsub('<', '&lt;').gsub('>', '&gt;')

  html = +""
  html << "<!doctype html>\n"
  html << "<html>\n<head>\n"
  html << "  <meta charset=\"utf-8\">\n"
  html << "  <title>Area Schematic - #{esc_name}</title>\n"
  html << "  <script src=\"https://unpkg.com/vis-network/standalone/umd/vis-network.min.js\"></script>\n"
  html << "  <style>\n"
  html << "    body { font-family: Arial, sans-serif; margin: 0; }\n"
  html << "    #toolbar { padding: 10px 14px; border-bottom: 1px solid #ddd; display: flex; gap: 8px; align-items: center; }\n"
  html << "    #network { width: 100%; height: calc(100vh - 52px); }\n"
  html << "    button { padding: 6px 10px; }\n"
  html << "    button.toggle-on { background: #4CAF50; color: #fff; border-color: #388E3C; }\n"
  html << "    button:disabled { opacity: 0.4; cursor: default; }\n"
  html << "    .sep { width: 1px; height: 24px; background: #ccc; }\n"
  html << "    .hint { color: #666; font-size: 12px; }\n"
  html << "  </style>\n"
  html << "</head>\n<body>\n"

  # Toolbar
  html << "  <div id=\"toolbar\">\n"
  html << "    <button id=\"saveBtn\">Save layout</button>\n"
  html << "    <button id=\"resetBtn\">Reset layout</button>\n"
  html << "    <div class=\"sep\"></div>\n"
  html << "    <button id=\"hideClosedBtn\">Hide closed</button>\n"
  html << "    <button id=\"autoArrangeBtn\">Auto-arrange links</button>\n"
  html << "    <div class=\"sep\"></div>\n"
  html << "    <button id=\"copyIdBtn\" disabled>Copy ID</button>\n"
  html << "    <span class=\"hint\" id=\"selInfo\"></span>\n"
  html << "    <div class=\"sep\"></div>\n"
  if layout_preloaded
    html << "    <span class=\"hint\" id=\"hintText\"><b>#{esc_name}</b> &mdash; Layout loaded. Drag to adjust, then Save to update. Hover for details.</span>\n"
  else
    html << "    <span class=\"hint\" id=\"hintText\"><b>#{esc_name}</b> &mdash; Drag nodes to arrange, then click Save layout.</span>\n"
  end
  html << "  </div>\n"
  html << "  <div id=\"network\"></div>\n"

  # Begin JavaScript
  html << "  <script>\n"
  html << "  (function() {\n"
  html << "    var payload = #{JSON.generate(html_payload)};\n"
  html << "    var layoutPreloaded = #{layout_preloaded};\n"
  html << "\n"

  # Canvas-based reservoir image generator
  html << "    function makeReservoirImage(name, percentFull) {\n"
  html << "      var canvas = document.createElement('canvas');\n"
  html << "      var w = 160, cylH = 80;\n"
  html << "      var nameLines = name.split('\\n');\n"
  html << "      var textH = nameLines.length * 16 + 12;\n"
  html << "      canvas.width = w;\n"
  html << "      canvas.height = cylH + textH;\n"
  html << "      var ctx = canvas.getContext('2d');\n"
  html << "      var cx = w / 2, halfW = 46, ry = 11;\n"
  html << "      var bodyTop = ry + 2, bodyBot = cylH - ry - 2;\n"
  html << "      var bodyH = bodyBot - bodyTop;\n"
  html << "      var pct = percentFull != null ? Math.max(0, Math.min(100, percentFull)) : 0;\n"
  html << "      var hasPct = percentFull != null;\n"
  html << "      var fillH = bodyH * pct / 100;\n"
  html << "      var fillTop = bodyBot - fillH;\n"
  html << "      var left = cx - halfW, right = cx + halfW;\n"
  html << "\n"
  html << "      ctx.fillStyle = '#DDEEFF';\n"
  html << "      ctx.fillRect(left, bodyTop, halfW * 2, bodyH);\n"
  html << "      if (hasPct && pct > 0) {\n"
  html << "        ctx.fillStyle = '#4488CC';\n"
  html << "        ctx.fillRect(left, fillTop, halfW * 2, fillH);\n"
  html << "      }\n"
  html << "      ctx.strokeStyle = '#4466AA';\n"
  html << "      ctx.lineWidth = 2;\n"
  html << "      ctx.beginPath(); ctx.moveTo(left, bodyTop); ctx.lineTo(left, bodyBot); ctx.stroke();\n"
  html << "      ctx.beginPath(); ctx.moveTo(right, bodyTop); ctx.lineTo(right, bodyBot); ctx.stroke();\n"
  html << "\n"
  html << "      ctx.fillStyle = (hasPct && pct > 0) ? '#4488CC' : '#DDEEFF';\n"
  html << "      ctx.beginPath(); ctx.ellipse(cx, bodyBot, halfW, ry, 0, 0, Math.PI * 2); ctx.fill();\n"
  html << "      ctx.strokeStyle = '#4466AA'; ctx.lineWidth = 2; ctx.stroke();\n"
  html << "\n"
  html << "      if (hasPct && pct > 0 && pct < 100) {\n"
  html << "        ctx.save(); ctx.globalAlpha = 0.7;\n"
  html << "        ctx.fillStyle = '#6AADDD';\n"
  html << "        ctx.beginPath(); ctx.ellipse(cx, fillTop, halfW, ry, 0, 0, Math.PI * 2); ctx.fill();\n"
  html << "        ctx.restore();\n"
  html << "        ctx.strokeStyle = '#4466AA'; ctx.lineWidth = 1;\n"
  html << "        ctx.beginPath(); ctx.ellipse(cx, fillTop, halfW, ry, 0, 0, Math.PI * 2); ctx.stroke();\n"
  html << "      }\n"
  html << "\n"
  html << "      ctx.fillStyle = (hasPct && pct >= 100) ? '#4488CC' : '#DDEEFF';\n"
  html << "      ctx.beginPath(); ctx.ellipse(cx, bodyTop, halfW, ry, 0, 0, Math.PI * 2); ctx.fill();\n"
  html << "      ctx.strokeStyle = '#4466AA'; ctx.lineWidth = 2; ctx.stroke();\n"
  html << "\n"
  html << "      if (hasPct && pct > 0) {\n"
  html << "        ctx.fillStyle = '#FFFFFF';\n"
  html << "        ctx.font = 'bold 14px Arial';\n"
  html << "        ctx.textAlign = 'center'; ctx.textBaseline = 'middle';\n"
  html << "        ctx.strokeStyle = '#1A3A5C'; ctx.lineWidth = 3;\n"
  html << "        ctx.strokeText(Math.round(pct) + '%', cx, bodyBot - bodyH / 2);\n"
  html << "        ctx.fillText(Math.round(pct) + '%', cx, bodyBot - bodyH / 2);\n"
  html << "      }\n"
  html << "\n"
  html << "      ctx.fillStyle = '#333'; ctx.font = '11px Arial';\n"
  html << "      ctx.textAlign = 'center'; ctx.textBaseline = 'top';\n"
  html << "      var ty = cylH + 6;\n"
  html << "      for (var i = 0; i < nameLines.length; i++) {\n"
  html << "        ctx.fillText(nameLines[i], cx, ty); ty += 16;\n"
  html << "      }\n"
  html << "      return canvas.toDataURL('image/png');\n"
  html << "    }\n"
  html << "\n"

  # Convert HTML title strings to DOM elements so vis-network renders them
  html << "    payload.nodes.forEach(function(node) {\n"
  html << "      if (typeof node.title === 'string' && node.title.length > 0) {\n"
  html << "        var div = document.createElement('div');\n"
  html << "        div.innerHTML = node.title;\n"
  html << "        node.title = div;\n"
  html << "      }\n"
  html << "    });\n"
  html << "\n"

  # Pre-process reservoir nodes
  html << "    try {\n"
  html << "      payload.nodes.forEach(function(node) {\n"
  html << "        if (node.nodeType === 'reservoir') {\n"
  html << "          node.image = makeReservoirImage(node.label, node.percentFull);\n"
  html << "          node.shape = 'image';\n"
  html << "          node.shapeProperties = { useImageSize: true };\n"
  html << "          node.label = '';\n"
  html << "        }\n"
  html << "      });\n"
  html << "    } catch(e) { console.error('Reservoir image error:', e); }\n"
  html << "\n"

  # Create vis-network
  html << "    var container = document.getElementById('network');\n"
  html << "    var nodes = new vis.DataSet(payload.nodes);\n"
  html << "    var edges = new vis.DataSet(payload.edges);\n"
  html << "    var data = { nodes: nodes, edges: edges };\n"
  html << "    var physicsOpts = layoutPreloaded\n"
  html << "      ? { enabled: false }\n"
  html << "      : { enabled: true, stabilization: { iterations: 1000 } };\n"
  html << "    var options = {\n"
  html << "      interaction: { hover: true, tooltipDelay: 150 },\n"
  html << "      layout: { improvedLayout: false },\n"
  html << "      edges: { smooth: false, arrows: { to: { enabled: true, scaleFactor: 0.5 } } },\n"
  html << "      physics: physicsOpts\n"
  html << "    };\n"
  html << "    var network = new vis.Network(container, data, options);\n"
  html << "\n"

  # Layout save/restore via localStorage
  html << "    var storageKey = 'area_schematic_layout_#{sanitize_filename(network_name)}';\n"
  html << "\n"
  html << "    function applySavedLayout(layout) {\n"
  html << "      if (!layout || !layout.positions) return false;\n"
  html << "      var ids = nodes.getIds();\n"
  html << "      var applied = false;\n"
  html << "      Object.keys(layout.positions).forEach(function(id) {\n"
  html << "        if (ids.indexOf(id) !== -1) {\n"
  html << "          var pos = layout.positions[id];\n"
  html << "          nodes.update({ id: id, x: pos.x, y: pos.y });\n"
  html << "          applied = true;\n"
  html << "        }\n"
  html << "      });\n"
  html << "      return applied;\n"
  html << "    }\n"
  html << "\n"
  html << "    function captureLayout() {\n"
  html << "      return { positions: network.getPositions() };\n"
  html << "    }\n"
  html << "\n"
  html << "    function saveLayoutToStorage() {\n"
  html << "      localStorage.setItem(storageKey, JSON.stringify(captureLayout()));\n"
  html << "    }\n"
  html << "\n"
  html << "    function loadLayoutFromStorage() {\n"
  html << "      var raw = localStorage.getItem(storageKey);\n"
  html << "      if (!raw) return;\n"
  html << "      try { applySavedLayout(JSON.parse(raw)); } catch (e) {}\n"
  html << "    }\n"
  html << "\n"
  html << "    network.on('dragEnd', function() { saveLayoutToStorage(); });\n"
  html << "\n"
  html << "    if (!layoutPreloaded) {\n"
  html << "      network.once('stabilizationIterationsDone', function() {\n"
  html << "        loadLayoutFromStorage();\n"
  html << "        network.setOptions({ physics: { enabled: false } });\n"
  html << "      });\n"
  html << "    }\n"
  html << "\n"

  # Save layout button — saves entire HTML with embedded positions
  html << "    var htmlFileName = '#{html_filename}';\n"
  html << "\n"
  html << "    function updateEmbeddedLayout() {\n"
  html << "      var el = document.getElementById('saved-layout');\n"
  html << "      if (el) el.textContent = JSON.stringify(network.getPositions());\n"
  html << "    }\n"
  html << "\n"
  html << "    function showSaveSuccess() {\n"
  html << "      var btn = document.getElementById('saveBtn');\n"
  html << "      btn.textContent = 'Saved!';\n"
  html << "      setTimeout(function() { btn.textContent = 'Save layout'; }, 2000);\n"
  html << "    }\n"
  html << "\n"
  html << "    document.getElementById('saveBtn').addEventListener('click', async function() {\n"
  html << "      updateEmbeddedLayout();\n"
  html << "      saveLayoutToStorage();\n"
  html << "      var fullHtml = '<!doctype html>\\n' + document.documentElement.outerHTML;\n"
  html << "      if (window.showSaveFilePicker) {\n"
  html << "        try {\n"
  html << "          var fh = await window.showSaveFilePicker({\n"
  html << "            suggestedName: htmlFileName,\n"
  html << "            types: [{ description: 'HTML file', accept: { 'text/html': ['.html'] } }]\n"
  html << "          });\n"
  html << "          var writable = await fh.createWritable();\n"
  html << "          await writable.write(fullHtml);\n"
  html << "          await writable.close();\n"
  html << "          showSaveSuccess();\n"
  html << "          return;\n"
  html << "        } catch (e) { if (e.name === 'AbortError') return; }\n"
  html << "      }\n"
  html << "      var blob = new Blob([fullHtml], { type: 'text/html' });\n"
  html << "      var a = document.createElement('a');\n"
  html << "      a.href = URL.createObjectURL(blob);\n"
  html << "      a.download = htmlFileName;\n"
  html << "      a.click(); URL.revokeObjectURL(a.href);\n"
  html << "    });\n"
  html << "\n"

  # Reset layout button
  html << "    document.getElementById('resetBtn').addEventListener('click', function() {\n"
  html << "      localStorage.removeItem(storageKey);\n"
  html << "      var el = document.getElementById('saved-layout');\n"
  html << "      if (el) el.textContent = '{}';\n"
  html << "      nodes.forEach(function(n) { nodes.update({ id: n.id, x: undefined, y: undefined }); });\n"
  html << "      network.setOptions({ physics: { enabled: true, stabilization: { iterations: 1000 } } });\n"
  html << "      network.stabilize(1000);\n"
  html << "      network.once('stabilizationIterationsDone', function() {\n"
  html << "        network.setOptions({ physics: { enabled: false } });\n"
  html << "      });\n"
  html << "    });\n"
  html << "\n"

  # Hide closed toggle
  html << "    var closedHidden = false;\n"
  html << "    var hiddenNodeIds = [];\n"
  html << "    var hiddenEdgeIds = [];\n"
  html << "\n"
  html << "    document.getElementById('hideClosedBtn').addEventListener('click', function() {\n"
  html << "      var btn = this;\n"
  html << "      if (!closedHidden) {\n"
  html << "        hiddenNodeIds = [];\n"
  html << "        hiddenEdgeIds = [];\n"
  html << "        nodes.forEach(function(n) {\n"
  html << "          if (n.nodeType === 'boundary' && n.isOpen === false) hiddenNodeIds.push(n.id);\n"
  html << "        });\n"
  html << "        hiddenNodeIds.forEach(function(nid) {\n"
  html << "          edges.forEach(function(e) {\n"
  html << "            if (e.from === nid || e.to === nid) hiddenEdgeIds.push(e.id);\n"
  html << "          });\n"
  html << "        });\n"
  html << "        hiddenEdgeIds.forEach(function(eid) { edges.update({ id: eid, hidden: true }); });\n"
  html << "        hiddenNodeIds.forEach(function(nid) { nodes.update({ id: nid, hidden: true }); });\n"
  html << "        btn.textContent = 'Show closed';\n"
  html << "        btn.classList.add('toggle-on');\n"
  html << "        closedHidden = true;\n"
  html << "      } else {\n"
  html << "        hiddenEdgeIds.forEach(function(eid) { edges.update({ id: eid, hidden: false }); });\n"
  html << "        hiddenNodeIds.forEach(function(nid) { nodes.update({ id: nid, hidden: false }); });\n"
  html << "        hiddenNodeIds = [];\n"
  html << "        hiddenEdgeIds = [];\n"
  html << "        btn.textContent = 'Hide closed';\n"
  html << "        btn.classList.remove('toggle-on');\n"
  html << "        closedHidden = false;\n"
  html << "      }\n"
  html << "    });\n"
  html << "\n"

  # Auto-arrange boundary links
  html << "    document.getElementById('autoArrangeBtn').addEventListener('click', function() {\n"
  html << "      var allEdges = edges.get();\n"
  html << "      var boundaryNodes = [];\n"
  html << "      nodes.forEach(function(n) {\n"
  html << "        if (n.nodeType === 'boundary') boundaryNodes.push(n);\n"
  html << "      });\n"
  html << "\n"
  html << "      var placements = {};\n"
  html << "      boundaryNodes.forEach(function(bn) {\n"
  html << "        var neighbors = [];\n"
  html << "        allEdges.forEach(function(e) {\n"
  html << "          if (e.from === bn.id) neighbors.push(e.to);\n"
  html << "          if (e.to === bn.id) neighbors.push(e.from);\n"
  html << "        });\n"
  html << "        if (neighbors.length < 2) return;\n"
  html << "        var posA = network.getPosition(neighbors[0]);\n"
  html << "        var posB = network.getPosition(neighbors[1]);\n"
  html << "        if (!posA || !posB) return;\n"
  html << "        var mx = (posA.x + posB.x) / 2;\n"
  html << "        var my = (posA.y + posB.y) / 2;\n"
  html << "        var pairKey = [neighbors[0], neighbors[1]].sort().join('|');\n"
  html << "        if (!placements[pairKey]) placements[pairKey] = { mx: mx, my: my, items: [] };\n"
  html << "        placements[pairKey].items.push(bn.id);\n"
  html << "      });\n"
  html << "\n"
  html << "      var MIN_SPACING = 30;\n"
  html << "      Object.keys(placements).forEach(function(key) {\n"
  html << "        var g = placements[key];\n"
  html << "        var parts = key.split('|');\n"
  html << "        var posA = network.getPosition(parts[0]);\n"
  html << "        var posB = network.getPosition(parts[1]);\n"
  html << "        var dx = posB.x - posA.x;\n"
  html << "        var dy = posB.y - posA.y;\n"
  html << "        var len = Math.sqrt(dx * dx + dy * dy) || 1;\n"
  html << "        var px = -dy / len;\n"
  html << "        var py = dx / len;\n"
  html << "        var count = g.items.length;\n"
  html << "        var totalSpan = (count - 1) * MIN_SPACING;\n"
  html << "        var startOff = -totalSpan / 2;\n"
  html << "        g.items.forEach(function(nid, i) {\n"
  html << "          var off = startOff + i * MIN_SPACING;\n"
  html << "          nodes.update({ id: nid, x: g.mx + px * off, y: g.my + py * off });\n"
  html << "        });\n"
  html << "      });\n"
  html << "      network.setOptions({ physics: { enabled: false } });\n"
  html << "      saveLayoutToStorage();\n"
  html << "    });\n"
  html << "\n"

  # Copy ID — track selection and enable/disable button
  html << "    var selectedObjectId = null;\n"
  html << "    var copyBtn = document.getElementById('copyIdBtn');\n"
  html << "    var selInfo = document.getElementById('selInfo');\n"
  html << "\n"
  html << "    function updateSelection(params) {\n"
  html << "      selectedObjectId = null;\n"
  html << "      if (params.nodes && params.nodes.length === 1) {\n"
  html << "        var n = nodes.get(params.nodes[0]);\n"
  html << "        if (n && n.objectId) {\n"
  html << "          selectedObjectId = n.objectId;\n"
  html << "          selInfo.textContent = n.objectId;\n"
  html << "          copyBtn.disabled = false;\n"
  html << "          return;\n"
  html << "        }\n"
  html << "      }\n"
  html << "      selInfo.textContent = '';\n"
  html << "      copyBtn.disabled = true;\n"
  html << "    }\n"
  html << "\n"
  html << "    network.on('selectNode', updateSelection);\n"
  html << "    network.on('deselectNode', updateSelection);\n"
  html << "\n"
  html << "    copyBtn.addEventListener('click', function() {\n"
  html << "      if (!selectedObjectId) return;\n"
  html << "      navigator.clipboard.writeText(selectedObjectId).then(function() {\n"
  html << "        copyBtn.textContent = 'Copied!';\n"
  html << "        setTimeout(function() { copyBtn.textContent = 'Copy ID'; }, 1500);\n"
  html << "      });\n"
  html << "    });\n"
  html << "\n"

  # Close script
  html << "  })();\n"
  html << "  </script>\n"

  # Embedded layout data — Ruby reads this block on next run to preserve positions
  layout_json = '{}'
  if layout_preloaded
    saved_positions = {}
    nodes_payload.each do |node|
      next if node[:x].nil? || node[:y].nil?
      saved_positions[node[:id]] = { x: node[:x], y: node[:y] }
    end
    layout_json = JSON.generate(saved_positions)
  end
  html << "  <script id=\"saved-layout\" type=\"application/json\">#{layout_json}</script>\n"
  html << "</body>\n</html>\n"

  html
end
